<?php

namespace Database\Seeders;

use App\Models\HistoryEvent;
use Illuminate\Database\Seeder;

class HistoryEventsSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            [1, '1919 – 1957', "Début de l'église baptiste yoruba au Togo", "L'église baptiste est née au Togo d'un petit groupe de yoruba assoiffés de la liberté. Ils étaient prêts à tout pour lever le défi de groupe minoritaire et de garantir l'avenir de leurs enfants. Encouragés par la Conférence Baptiste du Ghana (CBG) et motivés par l'exemple des méthodistes, ils se décideront à s'affranchir d'autres groupes chrétiens malgré de multiples conditions et restrictions en vigueur. C'était en 1919.\n\nPlus tard en 1955, par la visite du Rév John Idowu, l'idée de commencer une église baptiste vint. Mais il leur fallait impérativement un pasteur pour les diriger. Pressés par le besoin, ils accepteront un pasteur que l'association leur a proposé : le pasteur Samuel Amao, qui prit fonction en Décembre 1956. Il faudra attendre le 14 Avril 1957 pour pouvoir former un groupe baptiste séparé."],
            [2, '1957 – 1959', "La quête de l'autonomie totale", "Les baptistes Yoruba étaient séparés mais pas autonomes. Les autorités de l'Église Evangélique Presbytérienne gardaient toujours un œil de contrôle sur la jeune communauté. À l'intérieur, les crises augmentaient : un groupe d'anciens ne voulait plus du pasteur Ghanéen. Dans leur recherche de solution, ils contactèrent l'église baptiste de Paris, à l'insu du pasteur. L'association a finalement décidé de ramener le pasteur au Ghana et d'envoyer un pasteur très expérimenté du Nigéria — l'accalmie fut totale, les difficultés internes trouvèrent enfin des réponses."],
            [3, 'Décembre 1958', "Les progrès vers le baptisme biblique", "En décembre 1958, l'association affecta le pasteur Oladejo Owolabi pour les baptistes Yoruba dans le Togo français. Sous cet homme bien formé, soutenu par l'association, la mission et la communauté Yoruba, le changement ne tarda pas à venir. Avec l'aide de la Mission Baptiste Méridionale (MBM) et la Convention Baptiste du Nigéria, le nouveau pasteur travailla à l'établissement des principes bibliques dans la communauté, réorganisant l'église sur le modèle des églises baptistes méridionales."],
            [4, '1959 – 1964', "Organisation de l'église et appel aux missionnaires méridionaux", "En 1959, la mission protestante de Paris quitta définitivement le Togo, libérant l'église évangélique presbytérienne et toutes les autres missions protestantes. Un appel à évangéliser le Togo fut adressé à la Mission Baptiste méridionale. Le couple missionnaire Clayton Bond, intéressé par le Togo depuis son arrivée au Ghana en septembre 1958, fut affecté pour le Togo et arriva le 1er Octobre 1964, après une formation en langue française."],
            [5, '1964', 'Les problèmes resurgissent', "Après le départ du couple missionnaire, les tensions resurgirent. Les anciens qui avaient célébré le départ du pasteur Samuel Amao étaient déjà fatigués du nouveau pasteur, qui les avait mis de côté en tant que polygames non éligibles aux postes de direction. La tension entre les anciens pro-évangéliques et les nouveaux convertis au baptisme devint très grande, et tous attendaient le retour du couple missionnaire pour trancher."],
            [6, 'Octobre 1964', "La division de l'Eglise organisée", "Le couple missionnaire revint le 1er Octobre 1964 et fut immédiatement confronté à la crise. Craignant que le gouvernement ne ferme l'église en attendant la reconnaissance officielle, la situation se dénoua le 25 octobre : l'église se divisa, les jeunes se retirant pour former leur propre église — à peine un mois avant la reconnaissance officielle de l'église par l'État togolais."],
            [7, '24 Novembre 1964', "La reconnaissance officielle de l'église baptiste au Togo", "Le 24 Novembre 1964, la décision officielle est sortie : l'Association Église Baptiste est reconnue au Togo, couvrant toutes les initiatives baptistes du pays — les Baptistes Yoruba, les premiers convertis des missionnaires, l'ABWE (Association des Baptistes pour l'Évangélisation du Monde) et le début des Baptistes du Plein Évangile. C'était un projet missionnaire préparé de longue date, malgré les fermetures récurrentes de la frontière avec le Ghana depuis l'indépendance ghanéenne de 1957."],
            [8, 'Octobre 1964', 'Les arrangements au sujet du ministère', "Le 5 Octobre 1964, le couple missionnaire et le pasteur Oladejo Owolabi discutèrent longuement des orientations du ministère, insistant sur le fait qu'ils travailleraient avec tous les Togolais et pas seulement avec les Yoruba. Un culte d'accueil fut organisé pour le couple missionnaire le 11 octobre, et les deux groupes issus de la division restèrent couverts par le même texte de reconnaissance."],
            [9, '1964 – 1965', 'Les baptistes Yoruba membres de la conférence baptiste du Ghana', "Les baptistes Yoruba restèrent membres de la Conférence Baptiste du Ghana jusqu'à la fin de 1964. Cette année-là, le missionnaire Bond, installé au Togo, réclama l'annulation de l'association Lomé-Kéta : l'association Baptiste du Togo devenait libre et appartenait entièrement au Togo français. En 1965, une réconciliation forma l'association Baptiste Ebenezer, marquant le véritable début de l'église baptiste Yoruba au Togo."],
            [10, '1964 – 1986', 'Le début des églises baptistes évangéliques du Togo', "Le début de l'église baptiste évangélique du Togo — l'actuelle CBT — se situe en 1964. Entre 1964 et 1986, on note l'évangélisation des Togolais, l'implantation d'églises et la multiplication des associations : l'Association Ebenezer en 1965, puis l'Association des églises éwé en 1973. En 1978, le gouvernement togolais ferma les églises non enregistrées, poussant les associations Yoruba et Éwé à se refondre en une seule Association des Baptistes au Togo (ABT). L'évangélisation se poursuivit ensuite vers le nord du pays."],
            [11, '1988 – 2025', 'La naissance de la Convention Baptiste du Togo et son évolution', "Face aux coûts de déplacement des délégués du nord, l'éclatement des associations fut engagé lors d'une rencontre à Kouvé en 1984. Entre 1984 et 1988, une étude fut menée et une constitution rédigée. Les 24, 25 et 26 Mars 1988, la Convention Baptiste du Togo (CBT) est née à l'église baptiste du Boulevard, comptant six associations : A (Bethel), B (Agapé), C (Zion), D (la Vérité), E (le Chemin), F (Association du nord, devenue la Lumière, de Blitta à Dapaong). En 1989, la Mission Baptiste quitta officiellement le Togo, mais la direction resta entre les mains des expatriés jusqu'en 2002, date du départ du dernier missionnaire du centre baptiste de Morétan. Le diacre Koudakpo Komlan fut le premier dirigeant africain (secrétaire général dès 1991). Depuis, se sont succédé : Diacre Oke, Kwashie Amenudzie, Joseph Adjenou, Jean Sodehoudji, Bamerbanona Kadera, Remy A. Agossou, Pierre Ayawo Adossi, et l'actuel Président, le Rév. Elie Kokou Ayadome, élu le 3 avril 2025. Aujourd'hui, la CBT compte près de 55 000 fidèles adorant dans au moins 629 églises, réparties en 17 zones ecclésiastiques, et huit départements nationaux : Ministres de l'Évangile et Formation Théologique, Développement des Eglises, Mission-Évangélisation, Union Missionnaire des Hommes, Union Missionnaire des Femmes, Jeunesse-Sport-Loisirs, Développement des Enfants, et Projets et Écoles."],
        ];

        foreach ($events as [$order, $period, $title, $content]) {
            HistoryEvent::updateOrCreate(['order' => $order], [
                'period' => $period,
                'title' => $title,
                'content' => $content,
            ]);
        }
    }
}
